services:
  - type: web
    name: scraper-news-backend
    runtime: docker

    plan: free

    dockerfilePath: ./Dockerfile

    envVars:
      - key: PORT
        value: 10000

      - key: PYTHON_EXECUTABLE
        value: python3

      - key: PYTHON_SCRIPT_PATH
        value: ../scraper/main.py

      - key: MONGO_URI
        sync: false

      - key: MONGO_DB_NAME
        value: newspulse

      - key: FRONTEND_URL
        sync: false
